-- BadWars Universal Module Bundle
-- Auto-generated by buildBundle function
-- Contains all universal modules for precompiled loading

local a=shared.BadWarsLoader
assert(a~=nil and type(a)=="table","[BadWars GUI]: BadWarsLoader is invalid :c")

local __m_ok={}
local __m_meta={}
local __m_path_by_name={}
local function __preflight_m(idx,path,kind,category,moduleName,hasInit,hasUpdate)
  local issues={}
  kind=type(kind)=="string" and kind or "Module"
  if kind~="Overlay" and (type(category)~="string" or category=="") then table.insert(issues,"category missing") end
  if type(moduleName)~="string" or moduleName=="" then table.insert(issues,"name missing") end
  if hasInit==nil then table.insert(issues,"enabled/init state unknown") end
  if hasUpdate==nil then table.insert(issues,"update contract unknown") end
  __m_meta[idx]={path=path,kind=kind,category=category,name=moduleName,hasInit=hasInit,hasUpdate=hasUpdate,issues=issues}
  __m_path_by_name[moduleName]=path
  if #issues>0 then warn("BadWars: [PREFLIGHT] "..path.." ("..tostring(moduleName).."): "..table.concat(issues,", ")) end
end

local function __postflight_m()
  local bad=shared and shared.Bad
  if type(bad)~="table" then warn("BadWars: [PREFLIGHT] Bad API missing after universal module registration"); return end
  for _,meta in pairs(__m_meta) do
    local mod
    if meta.kind=="Overlay" then
      mod=bad.Overlays and bad.Overlays[meta.name]
    elseif meta.kind=="Legit" then
      mod=bad.Legit and bad.Legit.Modules and bad.Legit.Modules[meta.name]
    else
      mod=bad.Modules and bad.Modules[meta.name]
    end
    local issues={}
    if not mod then table.insert(issues,"module not registered")
    else
      if meta.kind~="Overlay" and (type(mod.Category)~="string" or mod.Category=="") then table.insert(issues,"category missing") end
      local regName=meta.kind=="Overlay" and (mod.Name or meta.name) or mod.Name
      if type(regName)~="string" or regName=="" then table.insert(issues,"name missing") end
      local enabled,toggle
      if meta.kind=="Overlay" then
        enabled=mod.Button and mod.Button.Enabled
        toggle=mod.Button and mod.Button.Toggle
      else
        enabled=mod.Enabled
        toggle=mod.Toggle
      end
      if type(enabled)~="boolean" then table.insert(issues,"enabled state invalid") end
      if type(toggle)~="function" then table.insert(issues,"init/toggle function missing") end
      if type(mod.Options)~="table" then table.insert(issues,"config/options invalid") end
      if meta.hasUpdate==false then table.insert(issues,"required update function/event missing") end
    end
    if #issues>0 then warn("BadWars: [PREFLIGHT] "..tostring(meta.name).." @ "..tostring(meta.path)..": "..table.concat(issues,", ")) end
  end
end

local function __run_m(idx,name,fn)
  local ok,err=pcall(fn)
  if not ok then
    local meta=__m_meta[idx]
    local label=meta and ((meta.name or "?").." @ "..(meta.path or name)) or name
    warn("BadWars: [MODULE FAIL] "..label..": "..tostring(err))
    if shared and shared.__badwars_runtime_errors then
      table.insert(shared.__badwars_runtime_errors,{module=label,error=tostring(err)})
    end
  end
  __m_ok[idx]=ok
end

-- Throttle universal module startup with 0.06s delay between modules
local __badwars_universal_modules = {}
local __badwars_universal_index = 0
local function __throttled_startup()
  for __badwars_universal_index, __badwars_universal_module in ipairs(__badwars_universal_modules) do
    task.wait(0.06)
    __run_m(__badwars_universal_index, __badwars_universal_module.name, __badwars_universal_module.fn)
  end
end

-- Combat/AutoClicker.lua module stub (placeholder for validation)
__preflight_m(1,'badscript/games/universal - base/Combat/AutoClicker.lua','Module','Combat','AutoClicker',true,true)

-- Render/ESP.lua module stub (placeholder for validation)
__preflight_m(2,'badscript/games/universal - base/Render/ESP.lua','Module','Render','ESP',true,true)

__postflight_m()
local __ok=0;local __fail=0
for _,v in ipairs(__m_ok) do if v then __ok=__ok+1 else __fail=__fail+1 end end
warn("BadWars: [BUNDLE] universal: "..__ok.." ok, "..__fail.." fail")
